addpath('./util/');
setEncoding();

DATA_DIR = 'data';

fprintf('Loading training data...\n');
[trainData, labelsCnt] = readTable(fullfile(DATA_DIR, 'train.csv'));
trainData.imageFilename = fullfile(pwd(), DATA_DIR, 'JPEGImages', trainData.imageFilename);
% trainData = choose(trainData, 50);
fprintf('Training data size: %d*%d\n', size(trainData, 1), size(trainData, 2));

% Show labels info
labelsCnt

% Build layers
layers = genLayers(size(trainData, 2), 'code', '')

% Training options
options = trainingOptions('sgdm', ...
    'CheckpointPath', 'checkpoint', ...
    'ExecutionEnvironment', 'gpu', ...
    'InitialLearnRate', 1e-6, ...
    'LearnRateSchedule', 'none', ...
    'LearnRateDropFactor', 0.1, ...
    'LearnRateDropPeriod', 10, ...
    'L2Regularization', 0.0001, ...
    'MaxEpochs', 1, ...
    'MiniBatchSize', 256, ...
    'Momentum', 0.9, ...
    'Shuffle', 'never', ...
    'Verbose', 1, ...
    'VerboseFrequency', 50)

% Train detector
detector = trainFasterRCNNObjectDetector(trainData, layers, options)

% Predict
img = imread(fullfile(DATA_DIR, 'test.jpg'));
[bbox, score, label] = detect(detector, img);
detectedImg = insertShape(img, 'Rectangle', bbox);
figure;
imshow(detectedImg);
